-- AlterTable
ALTER TABLE "Equipment" ADD COLUMN     "sameList" TEXT[] DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "serialNumber" DROP NOT NULL,
ALTER COLUMN "inventoryNumber" DROP NOT NULL,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "brand" DROP NOT NULL,
ALTER COLUMN "model" DROP NOT NULL,
ALTER COLUMN "category" DROP NOT NULL,
ALTER COLUMN "filesUrl" DROP NOT NULL,
ALTER COLUMN "imgUrl" DROP NOT NULL;
