name: backend-deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          set -e  # Останавливаем выполнение при ошибке
          
          cd /home/git/labhelp-backend
          
          echo "📥 Получаем последние изменения..."
          git pull origin main
          
          echo "📦 Устанавливаем зависимости..."
          npm install
          
          # Проверяем подключение к базе данных
          echo "🔗 Проверяем подключение к базе данных..."
          npx prisma db execute --stdin <<< "SELECT 1;" || {
            echo "❌ Ошибка подключения к базе данных"
            exit 1
          }
          
          # Проверяем здоровье БД
          echo "🏥 Проверяем здоровье базы данных..."
          npx prisma db execute --file scripts/verify_db_health.sql || {
            echo "⚠️ Проблемы с проверкой здоровья БД, продолжаем..."
          }
          
          # Дополнительная проверка и исправление проблемных миграций
          echo "🔧 Проверяем наличие проблемных миграций..."
          FAILED_MIGRATIONS=$(npx prisma migrate status 2>&1 | grep "failed" || true)
          if [ ! -z "$FAILED_MIGRATIONS" ]; then
            echo "⚠️ Найдены проблемные миграции, исправляем..."
            npx prisma db execute --file scripts/fix-failed-migration.sql || true
            npx prisma migrate resolve --applied 20250115000000_add_search_indexes || true
            echo "✅ Проблемные миграции исправлены"
          fi
          
          # Проверяем наличие новых миграций
          echo "🔍 Проверяем статус миграций..."
          MIGRATION_STATUS=$(npx prisma migrate status 2>&1 || true)
          echo "$MIGRATION_STATUS"
          
          # Выполняем миграции если они есть
          if echo "$MIGRATION_STATUS" | grep -q "Database schema is up to date"; then
            echo "✅ База данных актуальна, миграции не требуются"
          else
            echo "📦 Выполняем миграции базы данных..."
            npx prisma migrate deploy || {
              echo "❌ Ошибка выполнения миграций, пытаемся исправить..."
              # Исправляем проблемную миграцию поиска индексов
              npx prisma migrate resolve --applied 20250115000000_add_search_indexes || true
              npx prisma migrate resolve --applied 20250913150808_add_filter_tables || true
              npx prisma migrate deploy
            }
            echo "✅ Миграции выполнены успешно"
          fi
          
          # Проверяем и применяем индексы для оптимизации поиска (триграммы)
          echo "🔍 Проверяем наличие триграммных индексов..."
          TRGM_COUNT=$(npx prisma db execute --stdin <<< "SELECT COUNT(*) as count FROM pg_indexes WHERE schemaname = 'public' AND indexname LIKE '%_trgm%';" 2>/dev/null | grep -A 1 "count" | tail -1 | grep -oE '[0-9]+' || echo "0")
          echo "Найдено триграммных индексов: $TRGM_COUNT"
          
          if [ "$TRGM_COUNT" -lt "12" ]; then
            echo "📦 Применяем триграммные индексы для оптимизации ILIKE поиска (сейчас: $TRGM_COUNT, ожидается: 12)..."
            
            # Применяем индексы через JS скрипт (использует ту же логику что и seed)
            echo "📦 Применяем триграммные индексы через JS скрипт..."
            if node scripts/create-indexes.js; then
              echo "✅ JS скрипт выполнен успешно"
            else
              JS_EXIT_CODE=$?
              echo "⚠️ JS скрипт завершился с кодом $JS_EXIT_CODE"
              echo "⚠️ Пробуем альтернативный способ через SQL..."
              
              # Сначала проверяем/создаем расширение
              echo "🔧 Проверяем расширение pg_trgm..."
              npx prisma db execute --stdin <<< "CREATE EXTENSION IF NOT EXISTS pg_trgm;" 2>&1 || {
                echo "⚠️ Не удалось создать расширение pg_trgm (возможно, требуется права суперпользователя)"
              }
              
              # Применяем SQL скрипт как fallback
              if [ -f scripts/apply_search_indexes.sql ]; then
                npx prisma db execute --file scripts/apply_search_indexes.sql 2>&1 || {
                  echo "⚠️ Ошибка при применении SQL скрипта индексов"
                }
              else
                echo "⚠️ Файл scripts/apply_search_indexes.sql не найден"
              fi
            fi
            
            # Проверяем результат
            TRGM_COUNT_AFTER=$(npx prisma db execute --stdin <<< "SELECT COUNT(*) as count FROM pg_indexes WHERE schemaname = 'public' AND indexname LIKE '%_trgm%';" 2>/dev/null | grep -A 1 "count" | tail -1 | grep -oE '[0-9]+' || echo "0")
            echo "✅ Триграммные индексы применены (теперь: $TRGM_COUNT_AFTER)"
          else
            echo "✅ Триграммные индексы уже существуют ($TRGM_COUNT шт.)"
          fi
          
          # Финальная проверка структуры БД после деплоя
          echo "🔍 Выполняем финальную проверку структуры БД..."
          npx prisma db execute --file scripts/verify_db_health.sql || {
            echo "⚠️ Обнаружены проблемы со структурой БД, но продолжаем..."
          }
          
          # Генерируем клиент Prisma
          echo "🔄 Генерируем клиент Prisma..."
          npx prisma generate
          echo "✅ Клиент Prisma сгенерирован"
          
          # Перезапускаем приложение
          echo "🚀 Перезапускаем приложение..."
          pm2 restart index
          
          # Проверяем статус приложения
          echo "🔍 Проверяем статус приложения..."
          pm2 status
          
          echo "✅ Деплой завершен успешно!"